spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/induction2020/online-travel-booking-configuration.git

server:
  port: 8091